version: '2'

services:
  server:
    build: .
    image: jenkins:latest
    container_name: jenkins
    ports:
      - "8081:8080"
    environment:
      - TZ=Asia/Beijing
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ../../jenkins:/var/lib/jenkins
      - ../../dockers:/dockers
      - ../../.ssh/id_rsa:/home/jenkins/.ssh/id_rsa
      - ../../configs:/configs