FROM ubuntu:14.04

# Let's start with some basic stuff.
RUN apt-get update -qq && apt-get install -qqy \
	apt-transport-https \
	ca-certificates \
	curl \
	git \
	iptables \
	libxext-dev libxrender-dev libxtst-dev \
	ssh-askpass \
	unzip \
	wget \
	zip